#!/bin/sh
#SBATCH --nodes=1 --time=2-00:00:00
ncores=`sara-get-num-cores`
for ((i=1; i<=ncores; i++)) ; do
(
  while true ; do
    stopos next -m -p mlpool
      if [ "$STOPOS_RC" != "OK" ] ; then
        break
      fi
      if [ "$STOPOS_COMMITTED" -gt 3 ] ; then
        stopos remove -p mlpool
        continue
      fi
      Rscript mlfitscript.R $STOPOS_VALUE
      stopos remove -p mlpool
  done
) &
done
wait
